week_3/week_3_quiz.md

This PR adds the Week 3 quiz questions. Tagging @jdkent as a reviewer to confirm that I got the ABCD questions right.

ENH: Add week_3_quiz.md

---

break/viewABCD.md

This is the beginning of my attempt to make the notebook more annotated with markdown to provide additional context and minor changes to the code that ideally improve readability.

[ENH] add markdown annotations and make variables more verbose

---

week_5/week_5_quiz.md

I've added in the drop down answers to the week 5 ABCD specific questions (neurocognitive assessments lecture).

added correct answers to week 5 ABCD questions

---

week_3/week_3_quiz.md

This pull request adds the drop down answers with links to the relevant papers/time in the lecture where the question was answered.

[ENH] add answers to week 3 abcd questions

---

week_6/week_6_quiz.md

add drop down answers to the week 6 repronim questions.

[ENH] add week 6 repronim answers

---

week_4/week_4_quiz.md

Hi! I'm adding the week 4 quiz answers for both the ABCD & ReproNim content :)

added solutions for week 4 quiz

---

week_8/week_8_quiz.md

Add Zucker et al links

---

week_8/week_8_quiz.md

update links and a few grammar issues on the week 8 quiz markdown file

minor grammatical updates/link additions to week_8_quiz.md

---

week_8/week_8_quiz.md

Add missing link detailing the significant of BIDS dataset_descripotion.json files

add missing dataset_description.json link

---

break/clusterABCD.md

This adds an example jupyter notebook (in md format). It builds upon the data exercise, part 2, by
- further decomposing the subset data into categorical and numerical features,
- standardizing the data using a `MinMaxScaler`,
- computing a distance matrix using the Gower's distance,
- using this distance to perform hierarchical clustering of the feature space,
- plotting a dendrogram of this clustering, and
- prompting students to explain the feature correlations that they find.

ENH: Add clusterABCD.md example

---

week_9/week_9_quiz.md

Minor text updates to file header and some links.

Minor textual/link updates

---

week_9/week_9_quiz.md

Insert new lines after Q9 and Q10 headers

Week 9 updates

---

week_9/week_9_quiz.md

fix spelling error in Q10, add clarifying parenthetical for Q7

fix spelling error, add clarifying parenthetical

---

week_9/week_9_quiz.md

Merged both Q9 Bonus questions for simplicity in formatting

Merged bonus questions

---

week_9/week_9_quiz.md

- add a more verbose answer to question 6
- add explanation of unlocked files

[FIX] add more verbose answers/explanations

---

week_8/week_8_quiz.md

I copied the more verbose initial instructions from week 9 about the JupyterHub and added in the commands students would need to run for questions 6 and 10.

added solutions to week 8 repronim questions

---

week_10/week_10_quiz.md

Here are the repromin questions for week 10.

[ENH] add exercises for week 10

---

week_12/linear_mixed_effects.md
week_12/machine_learning.md
week_12/week_12_quiz.md

This adds the ABCD longitudinal modeling questions and associated notebook to help understand longitudinal models.

[ENH] week 12: add ABCD questions and code

---

week_2/week_2_year_2_bonus_DEAP_quiz.md
week_2/week_2_year_2_quiz.md

I'm updating the answer options based on the current version of DEAP.

adding updated version of DEAP quiz

---

week_4/week_4_year_1_quiz.md

Copy the Year 1 data exercise md file so that the archived site can still link to it.

Make copy of Week 4 Year 1 Quiz for archived site

---

week_4/week_4_quiz.md

update W4 questions

---

week_5/week_5_quiz.md

This PR revises week 5 questions by
- Providing sources for answers to the ABCD questions.
- Revising formatting for all answers.
- Directing readers to the [dirty_cat](https://dirty-cat.github.io/stable/) library for non-curated categorical variables.

Revise week 5 questions

---

week_10/week_10_quiz.md
week_10/week_10_year_1_quiz.md
week_10/week_10_year_2_quiz.md

This PR revises the week 10 questions. It's WIP because I've gone through the ABCD questions but haven't yet revised the ReproNim questions.

Revise week 10 questions

---

project_month_prep/downloadABCD.md

• Update suggested due date
• Add some relevant links referenced in the text
• Add a bit of context in text/instructions where helpful
• Fix some typos and punctuation

Textual edits

---

project_month_prep/clusterABCD.md

Only two changes were necessary - changing any reference from ABCD3 to ABCD4 and removing rows with null values from the final dataframe that's used for hierarchical clustering.

updated clusterABCD to reflect ABCD4 changes

---

week_12/linear_mixed_effects.md
week_12/week_12_quiz.md

no major errors 
`week_12_quiz.md` 
1. Make all formattings unified. Some were bulleted lists, some were task lists. Now they are all task lists.
2. Q6 had wrong wording. _Option B because the data is imputed **after** splitting_  NOT **before**
update explanations for some questions
`linear_mixed_effects.md` 
- change `copy()` to `deepcopy()`

week 12 exercise update
